-- Duplicar las tablas para prueba
CREATE TABLE XXX SELECT * FROM TABLA_ORIGEN; 

-- Agregar id con auto_increments en las tablas 
ALTER TABLE XXX add column id INT NOT NULL AUTO_INCREMENT FIRST, ADD primary KEY id(id);

-- Para las 3 tablas de cultivos resetie los id para que fuesen diferentes entre las tablas
SET @num := 1000;
UPDATE inf_cul_agric_clone SET id = @num := (@num+1);
ALTER TABLE inf_cul_agric_clone AUTO_INCREMENT =1;

-- id 1000 para las agricolas
-- id 2000 para las forrajeras
-- id 3000 para ornamentales

-- borrando los id que se registraron de mas en las 3 tablas
DELETE FROM inf_cul_agric_clone WHERE id > 1169;
DELETE FROM inf_cul_agric WHERE id > 1169;
DELETE FROM inf_cul_ornament WHERE id > 3055;

INSERT INTO inf_cul_agric_clone (id,	familia,	genero, especie, variedad, taxa, nombre_comun, reg_diversidad, endemico, nativo, introducido, naturalizado, agricola, ornamental,
forestal, maleza, anual, bianual, perenne, bulbosa, autogama, alogamas, entomofila, anemofila, artificial, landrace, semillas, vegetativas)
SELECT id,	familia,	genero, especie, variedad, taxa, nombre_comun, reg_diversidad, endemico, nativo, introducido, naturalizado, agricola, ornamental,
forestal, maleza, anual, bianual, perenne, bulbosa, autogama, alogamas, entomofila, anemofila, artificial, landrace, semillas, vegetativas FROM inf_cul_forraj;

	id	familia	genero especie variedad taxa nombre_comun reg_diversidad endemico nativo introducido naturalizado agricola ornamental
	forestal maleza anual bianual perenne bulbosa autogama alogamas entomofila anemofila artificial landrace semillas vegetativas

INSERT INTO cultivadas (id, taxa,  Cen, Cnati, Cin, Cnatu, Cag, Cor, Cfo, Cma, Cse, Cve, Can, Cbi, Cpe, Cbu, Cang, Calg, Cent, Cane, Cart, Clan, created_at, updated_at )
SELECT id, taxa, Cen, Cnati, Cin, Cnatu, Cag, Cor, Cfo, Cma, Cse, Cve, Can, Cbi, Cpe, Cbu, Cang, Calg, Cent, Cane, Cart, Clan, NOW(), NOW() FROM src_cultivadas;

INSERT INTO nativas (id, taxa, Nex, Np, Nv, Nr,created_at, updated_at)
SELECT id, taxa, Nex, Np, Nv, Nr,NOW(), NOW() FROM src_nativas;

INSERT INTO introducidas (`id`,`taxa`,`Ia`, `Io`,`If`,`Ime`,`Ima`,`In`,`created_at`, `updated_at`)
SELECT `id`,`taxa`,`Ia`, `Io`,`If`,`Ime`,`Ima`,`In`,NOW(), NOW() FROM src_introducidas;

-- Clasificacion de type.
	-- 1 Cultivadas
	-- 2 Introducidas
	-- 3 Nativas
	-- 4 Trangenicas

-- Ingresar la distribución por región a la tabla dstr_region

SELECT id, (SELECT 1), CASE  WHEN `` = 1 THEN  END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `` = 1 THEN  END IS NOT NULL UNION

INSERT INTO dstr_region (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 1), CASE  WHEN `1` = 1 THEN 1  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `1` = 1 THEN 1  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2` = 1 THEN 2  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `2` = 1 THEN 2  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3` = 1 THEN 3  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `3` = 1 THEN 3  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4` = 1 THEN 4  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `4` = 1 THEN 4  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5` = 1 THEN 5  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `5` = 1 THEN 5  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6` = 1 THEN 6  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `6` = 1 THEN 6  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7` = 1 THEN 7  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `7` = 1 THEN 7  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8` = 1 THEN 8  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `8` = 1 THEN 8  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9` = 1 THEN 9  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `9` = 1 THEN 9  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `10` = 1 THEN 10  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `10` = 1 THEN 10  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `11` = 1 THEN 11  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `11` = 1 THEN 11  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `12` = 1 THEN 12  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `12` = 1 THEN 12  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `13` = 1 THEN 13  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `13` = 1 THEN 13  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `14` = 1 THEN 14  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `14` = 1 THEN 14  END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `15` = 1 THEN 15  END , NOW(), NOW() FROM src_cultivadas WHERE CASE  WHEN `15` = 1 THEN 15  END IS NOT NULL;

INSERT INTO dstr_region (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 2), CASE  WHEN `1` = 1 THEN  1 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `1` = 1 THEN  1 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `2` = 1 THEN  2 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `2` = 1 THEN  2 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `3` = 1 THEN  3 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `3` = 1 THEN  3 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `4` = 1 THEN  4 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `4` = 1 THEN  4 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `5` = 1 THEN  5 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `5` = 1 THEN  5 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `6` = 1 THEN  6 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `6` = 1 THEN  6 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `7` = 1 THEN  7 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `7` = 1 THEN  7 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `8` = 1 THEN  8 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `8` = 1 THEN  8 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `9` = 1 THEN  9 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `9` = 1 THEN  9 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `10` = 1 THEN  10 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `10` = 1 THEN  10 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `11` = 1 THEN  11 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `11` = 1 THEN  11 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `12` = 1 THEN  12 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `12` = 1 THEN  12 END IS NOT NULL UNION
SELECT id, (SELECT 2), CASE  WHEN `13` = 1 THEN  13 END , NOW(), NOW() FROM src_introducidas WHERE CASE  WHEN `13` = 1 THEN  13 END IS NOT NULL;

INSERT INTO dstr_region (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 3), CASE  WHEN `1` = 1 THEN  1 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `1` = 1 THEN  1 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `2` = 1 THEN  2 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `2` = 1 THEN  2 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `3` = 1 THEN  3 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `3` = 1 THEN  3 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `4` = 1 THEN  4 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `4` = 1 THEN  4 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `5` = 1 THEN  5 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `5` = 1 THEN  5 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `6` = 1 THEN  6 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `6` = 1 THEN  6 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `7` = 1 THEN  7 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `7` = 1 THEN  7 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `8` = 1 THEN  8 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `8` = 1 THEN  8 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `9` = 1 THEN  9 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `9` = 1 THEN  9 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `10` = 1 THEN  10 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `10` = 1 THEN  10 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `11` = 1 THEN  11 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `11` = 1 THEN  11 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `12` = 1 THEN  12 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `12` = 1 THEN  12 END IS NOT NULL UNION
SELECT id, (SELECT 3), CASE  WHEN `13` = 1 THEN  13 END , NOW(), NOW() FROM src_nativas WHERE CASE  WHEN `13` = 1 THEN  13 END IS NOT NULL;

-- Provincia  
--Cultivadas agrícolas

SELECT id, (SELECT 1), CASE  WHEN `` = 1 THEN  END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `` = 1 THEN  END IS NOT NULL;

INSERT INTO dstr_provincia (id_taxa, type, code, created_at, updated_at)

SELECT id, (SELECT 1), CASE  WHEN `11` = 1 THEN  11 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `11` = 1 THEN  11 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `14` = 1 THEN  14 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `14` = 1 THEN  14 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `21` = 1 THEN  21 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `21` = 1 THEN  21 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `22` = 1 THEN  22 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `22` = 1 THEN  22 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `23` = 1 THEN  23 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `23` = 1 THEN  23 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `31` = 1 THEN  31 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `31` = 1 THEN  31 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `32` = 1 THEN  32 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `32` = 1 THEN  32 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `33` = 1 THEN  33 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `33` = 1 THEN  33 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `41` = 1 THEN  41 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `41` = 1 THEN  41 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `42` = 1 THEN  42 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `42` = 1 THEN  42 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `43` = 1 THEN  43 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `43` = 1 THEN  43 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `51` = 1 THEN  51 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `51` = 1 THEN  51 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `52` = 1 THEN  52 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `52` = 1 THEN  52 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `53` = 1 THEN  53 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `53` = 1 THEN  53 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `54` = 1 THEN  54 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `54` = 1 THEN  54 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `55` = 1 THEN  55 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `55` = 1 THEN  55 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `56` = 1 THEN  56 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `56` = 1 THEN  56 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `57` = 1 THEN  57 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `57` = 1 THEN  57 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `61` = 1 THEN  61 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `61` = 1 THEN  61 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `62` = 1 THEN  62 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `62` = 1 THEN  62 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `63` = 1 THEN  63 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `63` = 1 THEN  63 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `71` = 1 THEN  71 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `71` = 1 THEN  71 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `72` = 1 THEN  72 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `72` = 1 THEN  72 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `73` = 1 THEN  73 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `73` = 1 THEN  73 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `74` = 1 THEN  74 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `74` = 1 THEN  74 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `81` = 1 THEN  81 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `81` = 1 THEN  81 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `82` = 1 THEN  82 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `82` = 1 THEN  82 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `83` = 1 THEN  83 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `83` = 1 THEN  83 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `84` = 1 THEN  84 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `84` = 1 THEN  84 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `91` = 1 THEN  91 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `91` = 1 THEN  91 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `92` = 1 THEN  92 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `92` = 1 THEN  92 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `101` = 1 THEN  101 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `101` = 1 THEN  101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `102` = 1 THEN  102 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `102` = 1 THEN  102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `103` = 1 THEN  103 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `103` = 1 THEN  103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `104` = 1 THEN  104 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `104` = 1 THEN  104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `111` = 1 THEN  111 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `111` = 1 THEN  111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `112` = 1 THEN  112 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `112` = 1 THEN  112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `113` = 1 THEN  113 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `113` = 1 THEN  113 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `114` = 1 THEN  114 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `114` = 1 THEN  114 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `121` = 1 THEN  121 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `121` = 1 THEN  121 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `122` = 1 THEN  122 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `122` = 1 THEN  122 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `123` = 1 THEN  123 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `123` = 1 THEN  123 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `124` = 1 THEN  124 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `124` = 1 THEN  124 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `131` = 1 THEN  131 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `131` = 1 THEN  131 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `132` = 1 THEN  132 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `132` = 1 THEN  132 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `133` = 1 THEN  133 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `133` = 1 THEN  133 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `134` = 1 THEN  134 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `134` = 1 THEN  134 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `135` = 1 THEN  135 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `135` = 1 THEN  135 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `136` = 1 THEN  136 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `136` = 1 THEN  136 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `141` = 1 THEN  141 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `141` = 1 THEN  141 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `142` = 1 THEN  142 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `142` = 1 THEN  142 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `151` = 1 THEN  151 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `151` = 1 THEN  151 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `152` = 1 THEN  152 END , NOW(), NOW() FROM src_cultivad_agric_dstr WHERE CASE  WHEN `152` = 1 THEN  152 END IS NOT NULL ;



--Cultivadas forestales
SELECT id, (SELECT 1), CASE  WHEN `` = 1 THEN  END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `` = 1 THEN  END IS NOT NULL;

INSERT INTO dstr_provincia (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 1), CASE  WHEN `11` = 1 THEN  11 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `11` = 1 THEN  11 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `14` = 1 THEN  14 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `14` = 1 THEN  14 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `31` = 1 THEN  31 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `31` = 1 THEN  31 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `33` = 1 THEN  33 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `33` = 1 THEN  33 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `41` = 1 THEN  41 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `41` = 1 THEN  41 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `42` = 1 THEN  42 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `42` = 1 THEN  42 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `43` = 1 THEN  43 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `43` = 1 THEN  43 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `51` = 1 THEN  51 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `51` = 1 THEN  51 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `53` = 1 THEN  53 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `53` = 1 THEN  53 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `54` = 1 THEN  54 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `54` = 1 THEN  54 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `55` = 1 THEN  55 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `55` = 1 THEN  55 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `56` = 1 THEN  56 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `56` = 1 THEN  56 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `57` = 1 THEN  57 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `57` = 1 THEN  57 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `61` = 1 THEN  61 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `61` = 1 THEN  61 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `62` = 1 THEN  62 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `62` = 1 THEN  62 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `63` = 1 THEN  63 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `63` = 1 THEN  63 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `71` = 1 THEN  71 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `71` = 1 THEN  71 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `72` = 1 THEN  72 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `72` = 1 THEN  72 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `73` = 1 THEN  73 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `73` = 1 THEN  73 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `74` = 1 THEN  74 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `74` = 1 THEN  74 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `81` = 1 THEN  81 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `81` = 1 THEN  81 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `82` = 1 THEN  82 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `82` = 1 THEN  82 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `83` = 1 THEN  83 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `83` = 1 THEN  83 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `84` = 1 THEN  84 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `84` = 1 THEN  84 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `91` = 1 THEN  91 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `91` = 1 THEN  91 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `92` = 1 THEN  92 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `92` = 1 THEN  92 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `101` = 1 THEN  101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `101` = 1 THEN  101 END IS NOT NULL;

INSERT INTO dstr_comuna (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 1), CASE  WHEN `1101` = 1 THEN  1101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `1101` = 1 THEN  1101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1401` = 1 THEN  1401 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `1401` = 1 THEN  1401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1404` = 1 THEN  1404 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `1404` = 1 THEN  1404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1405` = 1 THEN  1405 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `1405` = 1 THEN  1405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2104` = 1 THEN  2104 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `2104` = 1 THEN  2104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2203` = 1 THEN  2203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `2203` = 1 THEN  2203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2302` = 1 THEN  2302 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `2302` = 1 THEN  2302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3101` = 1 THEN  3101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3101` = 1 THEN  3101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3102` = 1 THEN  3102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3102` = 1 THEN  3102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3103` = 1 THEN  3103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3103` = 1 THEN  3103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3201` = 1 THEN  3201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3201` = 1 THEN  3201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3301` = 1 THEN  3301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3301` = 1 THEN  3301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3302` = 1 THEN  3302 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3302` = 1 THEN  3302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3303` = 1 THEN  3303 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3303` = 1 THEN  3303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3304` = 1 THEN  3304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `3304` = 1 THEN  3304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4201` = 1 THEN  4201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4201` = 1 THEN  4201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4202` = 1 THEN  4202 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4202` = 1 THEN  4202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4203` = 1 THEN  4203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4203` = 1 THEN  4203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4204` = 1 THEN  4204 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4204` = 1 THEN  4204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4301` = 1 THEN  4301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4301` = 1 THEN  4301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4303` = 1 THEN  4303 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4303` = 1 THEN  4303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4304` = 1 THEN  4304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `4304` = 1 THEN  4304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5101` = 1 THEN  5101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5101` = 1 THEN  5101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5102` = 1 THEN  5102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5102` = 1 THEN  5102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5103` = 1 THEN  5103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5103` = 1 THEN  5103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5105` = 1 THEN  5105 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5105` = 1 THEN  5105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5107` = 1 THEN  5107 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5107` = 1 THEN  5107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5109` = 1 THEN  5109 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5109` = 1 THEN  5109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5201` = 1 THEN  5201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5201` = 1 THEN  5201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5301` = 1 THEN  5301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5301` = 1 THEN  5301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5304` = 1 THEN  5304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5304` = 1 THEN  5304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5401` = 1 THEN  5401 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5401` = 1 THEN  5401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5402` = 1 THEN  5402 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5402` = 1 THEN  5402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5403` = 1 THEN  5403 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5403` = 1 THEN  5403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5404` = 1 THEN  5404 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5404` = 1 THEN  5404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5501` = 1 THEN  5501 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5501` = 1 THEN  5501 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5502` = 1 THEN  5502 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5502` = 1 THEN  5502 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5503` = 1 THEN  5503 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5503` = 1 THEN  5503 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5506` = 1 THEN  5506 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5506` = 1 THEN  5506 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5601` = 1 THEN  5601 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5601` = 1 THEN  5601 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5602` = 1 THEN  5602 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5602` = 1 THEN  5602 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5603` = 1 THEN  5603 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5603` = 1 THEN  5603 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5604` = 1 THEN  5604 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5604` = 1 THEN  5604 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5605` = 1 THEN  5605 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5605` = 1 THEN  5605 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5606` = 1 THEN  5606 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5606` = 1 THEN  5606 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5702` = 1 THEN  5702 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5702` = 1 THEN  5702 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5703` = 1 THEN  5703 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5703` = 1 THEN  5703 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5704` = 1 THEN  5704 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5704` = 1 THEN  5704 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5705` = 1 THEN  5705 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5705` = 1 THEN  5705 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5801` = 1 THEN  5801 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5801` = 1 THEN  5801 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5802` = 1 THEN  5802 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5802` = 1 THEN  5802 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5803` = 1 THEN  5803 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5803` = 1 THEN  5803 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5804` = 1 THEN  5804 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `5804` = 1 THEN  5804 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6102` = 1 THEN  6102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6102` = 1 THEN  6102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6103` = 1 THEN  6103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6103` = 1 THEN  6103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6104` = 1 THEN  6104 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6104` = 1 THEN  6104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6105` = 1 THEN  6105 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6105` = 1 THEN  6105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6107` = 1 THEN  6107 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6107` = 1 THEN  6107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6108` = 1 THEN  6108 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6108` = 1 THEN  6108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6109` = 1 THEN  6109 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6109` = 1 THEN  6109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6110` = 1 THEN  6110 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6110` = 1 THEN  6110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6112` = 1 THEN  6112 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6112` = 1 THEN  6112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6113` = 1 THEN  6113 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6113` = 1 THEN  6113 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6115` = 1 THEN  6115 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6115` = 1 THEN  6115 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6116` = 1 THEN  6116 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6116` = 1 THEN  6116 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6117` = 1 THEN  6117 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6117` = 1 THEN  6117 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6201` = 1 THEN  6201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6201` = 1 THEN  6201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6202` = 1 THEN  6202 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6202` = 1 THEN  6202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6203` = 1 THEN  6203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6203` = 1 THEN  6203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6204` = 1 THEN  6204 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6204` = 1 THEN  6204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6205` = 1 THEN  6205 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6205` = 1 THEN  6205 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6206` = 1 THEN  6206 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6206` = 1 THEN  6206 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6301` = 1 THEN  6301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6301` = 1 THEN  6301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6302` = 1 THEN  6302 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6302` = 1 THEN  6302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6303` = 1 THEN  6303 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6303` = 1 THEN  6303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6304` = 1 THEN  6304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6304` = 1 THEN  6304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6305` = 1 THEN  6305 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6305` = 1 THEN  6305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6306` = 1 THEN  6306 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6306` = 1 THEN  6306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6307` = 1 THEN  6307 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6307` = 1 THEN  6307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6308` = 1 THEN  6308 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6308` = 1 THEN  6308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6309` = 1 THEN  6309 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6309` = 1 THEN  6309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6310` = 1 THEN  6310 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `6310` = 1 THEN  6310 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7101` = 1 THEN  7101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7101` = 1 THEN  7101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7102` = 1 THEN  7102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7102` = 1 THEN  7102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7103` = 1 THEN  7103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7103` = 1 THEN  7103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7104` = 1 THEN  7104 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7104` = 1 THEN  7104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7105` = 1 THEN  7105 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7105` = 1 THEN  7105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7106` = 1 THEN  7106 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7106` = 1 THEN  7106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7107` = 1 THEN  7107 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7107` = 1 THEN  7107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7108` = 1 THEN  7108 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7108` = 1 THEN  7108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7109` = 1 THEN  7109 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7109` = 1 THEN  7109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7110` = 1 THEN  7110 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7110` = 1 THEN  7110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7201` = 1 THEN  7201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7201` = 1 THEN  7201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7202` = 1 THEN  7202 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7202` = 1 THEN  7202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7203` = 1 THEN  7203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7203` = 1 THEN  7203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7301` = 1 THEN  7301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7301` = 1 THEN  7301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7302` = 1 THEN  7302 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7302` = 1 THEN  7302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7303` = 1 THEN  7303 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7303` = 1 THEN  7303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7304` = 1 THEN  7304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7304` = 1 THEN  7304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7305` = 1 THEN  7305 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7305` = 1 THEN  7305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7306` = 1 THEN  7306 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7306` = 1 THEN  7306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7307` = 1 THEN  7307 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7307` = 1 THEN  7307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7308` = 1 THEN  7308 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7308` = 1 THEN  7308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7309` = 1 THEN  7309 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7309` = 1 THEN  7309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7401` = 1 THEN  7401 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7401` = 1 THEN  7401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7402` = 1 THEN  7402 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7402` = 1 THEN  7402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7403` = 1 THEN  7403 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7403` = 1 THEN  7403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7404` = 1 THEN  7404 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7404` = 1 THEN  7404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7405` = 1 THEN  7405 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7405` = 1 THEN  7405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7406` = 1 THEN  7406 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7406` = 1 THEN  7406 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7407` = 1 THEN  7407 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7407` = 1 THEN  7407 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7408` = 1 THEN  7408 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `7408` = 1 THEN  7408 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8101` = 1 THEN  8101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8101` = 1 THEN  8101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8102` = 1 THEN  8102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8102` = 1 THEN  8102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8103` = 1 THEN  8103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8103` = 1 THEN  8103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8104` = 1 THEN  8104 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8104` = 1 THEN  8104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8105` = 1 THEN  8105 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8105` = 1 THEN  8105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8106` = 1 THEN  8106 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8106` = 1 THEN  8106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8107` = 1 THEN  8107 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8107` = 1 THEN  8107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8108` = 1 THEN  8108 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8108` = 1 THEN  8108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8109` = 1 THEN  8109 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8109` = 1 THEN  8109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8111` = 1 THEN  8111 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8111` = 1 THEN  8111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8112` = 1 THEN  8112 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8112` = 1 THEN  8112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8201` = 1 THEN  8201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8201` = 1 THEN  8201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8202` = 1 THEN  8202 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8202` = 1 THEN  8202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8203` = 1 THEN  8203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8203` = 1 THEN  8203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8204` = 1 THEN  8204 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8204` = 1 THEN  8204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8205` = 1 THEN  8205 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8205` = 1 THEN  8205 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8206` = 1 THEN  8206 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8206` = 1 THEN  8206 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8207` = 1 THEN  8207 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8207` = 1 THEN  8207 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8301` = 1 THEN  8301 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8301` = 1 THEN  8301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8302` = 1 THEN  8302 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8302` = 1 THEN  8302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8303` = 1 THEN  8303 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8303` = 1 THEN  8303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8304` = 1 THEN  8304 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8304` = 1 THEN  8304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8305` = 1 THEN  8305 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8305` = 1 THEN  8305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8306` = 1 THEN  8306 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8306` = 1 THEN  8306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8307` = 1 THEN  8307 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8307` = 1 THEN  8307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8308` = 1 THEN  8308 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8308` = 1 THEN  8308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8309` = 1 THEN  8309 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8309` = 1 THEN  8309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8310` = 1 THEN  8310 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8310` = 1 THEN  8310 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8311` = 1 THEN  8311 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8311` = 1 THEN  8311 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8312` = 1 THEN  8312 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8312` = 1 THEN  8312 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8313` = 1 THEN  8313 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8313` = 1 THEN  8313 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8314` = 1 THEN  8314 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8314` = 1 THEN  8314 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8401` = 1 THEN  8401 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8401` = 1 THEN  8401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8402` = 1 THEN  8402 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8402` = 1 THEN  8402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8403` = 1 THEN  8403 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8403` = 1 THEN  8403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8404` = 1 THEN  8404 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8404` = 1 THEN  8404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8405` = 1 THEN  8405 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8405` = 1 THEN  8405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8406` = 1 THEN  8406 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8406` = 1 THEN  8406 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8407` = 1 THEN  8407 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8407` = 1 THEN  8407 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8408` = 1 THEN  8408 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8408` = 1 THEN  8408 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8409` = 1 THEN  8409 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8409` = 1 THEN  8409 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8410` = 1 THEN  8410 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8410` = 1 THEN  8410 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8411` = 1 THEN  8411 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8411` = 1 THEN  8411 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8412` = 1 THEN  8412 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8412` = 1 THEN  8412 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8413` = 1 THEN  8413 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8413` = 1 THEN  8413 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8414` = 1 THEN  8414 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8414` = 1 THEN  8414 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8415` = 1 THEN  8415 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8415` = 1 THEN  8415 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8416` = 1 THEN  8416 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8416` = 1 THEN  8416 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8417` = 1 THEN  8417 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8417` = 1 THEN  8417 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8418` = 1 THEN  8418 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8418` = 1 THEN  8418 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8419` = 1 THEN  8419 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8419` = 1 THEN  8419 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8420` = 1 THEN  8420 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8420` = 1 THEN  8420 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8421` = 1 THEN  8421 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `8421` = 1 THEN  8421 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9101` = 1 THEN  9101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9101` = 1 THEN  9101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9102` = 1 THEN  9102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9102` = 1 THEN  9102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9103` = 1 THEN  9103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9103` = 1 THEN  9103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9104` = 1 THEN  9104 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9104` = 1 THEN  9104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9105` = 1 THEN  9105 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9105` = 1 THEN  9105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9106` = 1 THEN  9106 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9106` = 1 THEN  9106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9107` = 1 THEN  9107 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9107` = 1 THEN  9107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9108` = 1 THEN  9108 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9108` = 1 THEN  9108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9109` = 1 THEN  9109 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9109` = 1 THEN  9109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9110` = 1 THEN  9110 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9110` = 1 THEN  9110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9111` = 1 THEN  9111 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9111` = 1 THEN  9111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9112` = 1 THEN  9112 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9112` = 1 THEN  9112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9113` = 1 THEN  9113 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9113` = 1 THEN  9113 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9114` = 1 THEN  9114 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9114` = 1 THEN  9114 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9115` = 1 THEN  9115 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9115` = 1 THEN  9115 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9116` = 1 THEN  9116 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9116` = 1 THEN  9116 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9117` = 1 THEN  9117 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9117` = 1 THEN  9117 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9118` = 1 THEN  9118 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9118` = 1 THEN  9118 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9119` = 1 THEN  9119 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9119` = 1 THEN  9119 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9120` = 1 THEN  9120 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9120` = 1 THEN  9120 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9121` = 1 THEN  9121 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9121` = 1 THEN  9121 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9201` = 1 THEN  9201 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9201` = 1 THEN  9201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9202` = 1 THEN  9202 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9202` = 1 THEN  9202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9203` = 1 THEN  9203 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9203` = 1 THEN  9203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9204` = 1 THEN  9204 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9204` = 1 THEN  9204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9205` = 1 THEN  9205 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9205` = 1 THEN  9205 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9206` = 1 THEN  9206 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9206` = 1 THEN  9206 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9207` = 1 THEN  9207 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9207` = 1 THEN  9207 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9208` = 1 THEN  9208 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9208` = 1 THEN  9208 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9209` = 1 THEN  9209 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9209` = 1 THEN  9209 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9210` = 1 THEN  9210 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9210` = 1 THEN  9210 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9211` = 1 THEN  9211 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `9211` = 1 THEN  9211 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `10101` = 1 THEN  10101 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `10101` = 1 THEN  10101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `10102` = 1 THEN  10102 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `10102` = 1 THEN  10102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `10103` = 1 THEN  10103 END , NOW(), NOW() FROM src_cult_forestal_dstr WHERE CASE  WHEN `10103` = 1 THEN  10103 END IS NOT NULL;

-- para las vides
SELECT id, (SELECT 1), CASE  WHEN `` = 1 THEN  END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `` = 1 THEN  END IS NOT NULL UNION

INSERT INTO dstr_provincia (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 1), CASE  WHEN `11` = 1 THEN  11 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `11` = 1 THEN  11 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `14` = 1 THEN  14 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `14` = 1 THEN  14 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `31` = 1 THEN  31 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `31` = 1 THEN  31 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `33` = 1 THEN  33 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `33` = 1 THEN  33 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `42` = 1 THEN  42 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `42` = 1 THEN  42 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `43` = 1 THEN  43 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `43` = 1 THEN  43 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `51` = 1 THEN  51 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `51` = 1 THEN  51 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `53` = 1 THEN  53 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `53` = 1 THEN  53 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `54` = 1 THEN  54 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `54` = 1 THEN  54 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `55` = 1 THEN  55 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `55` = 1 THEN  55 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `56` = 1 THEN  56 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `56` = 1 THEN  56 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `57` = 1 THEN  57 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `57` = 1 THEN  57 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `61` = 1 THEN  61 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `61` = 1 THEN  61 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `62` = 1 THEN  62 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `62` = 1 THEN  62 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `63` = 1 THEN  63 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `63` = 1 THEN  63 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `71` = 1 THEN  71 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `71` = 1 THEN  71 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `72` = 1 THEN  72 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `72` = 1 THEN  72 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `73` = 1 THEN  73 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `73` = 1 THEN  73 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `74` = 1 THEN  74 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `74` = 1 THEN  74 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `81` = 1 THEN  81 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `81` = 1 THEN  81 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `82` = 1 THEN  82 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `82` = 1 THEN  82 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `84` = 1 THEN  84 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `84` = 1 THEN  84 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `91` = 1 THEN  91 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `91` = 1 THEN  91 END IS NOT NULL;

INSERT INTO dstr_comuna (id_taxa, type, code, created_at, updated_at)
SELECT id, (SELECT 1), CASE  WHEN `1101` = 1 THEN  1101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `1101` = 1 THEN  1101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1401` = 1 THEN  1401 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `1401` = 1 THEN  1401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1403` = 1 THEN  1403 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `1403` = 1 THEN  1403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1404` = 1 THEN  1404 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `1404` = 1 THEN  1404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `1405` = 1 THEN  1405 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `1405` = 1 THEN  1405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2101` = 1 THEN  2101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `2101` = 1 THEN  2101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2104` = 1 THEN  2104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `2104` = 1 THEN  2104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2203` = 1 THEN  2203 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `2203` = 1 THEN  2203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `2302` = 1 THEN  2302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `2302` = 1 THEN  2302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3101` = 1 THEN  3101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3101` = 1 THEN  3101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3102` = 1 THEN  3102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3102` = 1 THEN  3102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3103` = 1 THEN  3103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3103` = 1 THEN  3103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3201` = 1 THEN  3201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3201` = 1 THEN  3201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3202` = 1 THEN  3202 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3202` = 1 THEN  3202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3301` = 1 THEN  3301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3301` = 1 THEN  3301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3302` = 1 THEN  3302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3302` = 1 THEN  3302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3303` = 1 THEN  3303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3303` = 1 THEN  3303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `3304` = 1 THEN  3304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `3304` = 1 THEN  3304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4101` = 1 THEN  4101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4101` = 1 THEN  4101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4102` = 1 THEN  4102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4102` = 1 THEN  4102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4103` = 1 THEN  4103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4103` = 1 THEN  4103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4104` = 1 THEN  4104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4104` = 1 THEN  4104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4105` = 1 THEN  4105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4105` = 1 THEN  4105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4106` = 1 THEN  4106 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4106` = 1 THEN  4106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4201` = 1 THEN  4201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4201` = 1 THEN  4201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4202` = 1 THEN  4202 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4202` = 1 THEN  4202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4203` = 1 THEN  4203 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4203` = 1 THEN  4203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4204` = 1 THEN  4204 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4204` = 1 THEN  4204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4301` = 1 THEN  4301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4301` = 1 THEN  4301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4302` = 1 THEN  4302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4302` = 1 THEN  4302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4303` = 1 THEN  4303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4303` = 1 THEN  4303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4304` = 1 THEN  4304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4304` = 1 THEN  4304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `4305` = 1 THEN  4305 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `4305` = 1 THEN  4305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5101` = 1 THEN  5101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5101` = 1 THEN  5101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5102` = 1 THEN  5102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5102` = 1 THEN  5102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5103` = 1 THEN  5103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5103` = 1 THEN  5103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5105` = 1 THEN  5105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5105` = 1 THEN  5105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5107` = 1 THEN  5107 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5107` = 1 THEN  5107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5109` = 1 THEN  5109 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5109` = 1 THEN  5109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5201` = 1 THEN  5201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5201` = 1 THEN  5201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5301` = 1 THEN  5301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5301` = 1 THEN  5301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5302` = 1 THEN  5302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5302` = 1 THEN  5302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5303` = 1 THEN  5303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5303` = 1 THEN  5303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5304` = 1 THEN  5304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5304` = 1 THEN  5304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5401` = 1 THEN  5401 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5401` = 1 THEN  5401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5402` = 1 THEN  5402 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5402` = 1 THEN  5402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5403` = 1 THEN  5403 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5403` = 1 THEN  5403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5404` = 1 THEN  5404 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5404` = 1 THEN  5404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5405` = 1 THEN  5405 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5405` = 1 THEN  5405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5501` = 1 THEN  5501 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5501` = 1 THEN  5501 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5502` = 1 THEN  5502 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5502` = 1 THEN  5502 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5503` = 1 THEN  5503 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5503` = 1 THEN  5503 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5506` = 1 THEN  5506 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5506` = 1 THEN  5506 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5601` = 1 THEN  5601 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5601` = 1 THEN  5601 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5602` = 1 THEN  5602 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5602` = 1 THEN  5602 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5603` = 1 THEN  5603 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5603` = 1 THEN  5603 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5604` = 1 THEN  5604 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5604` = 1 THEN  5604 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5605` = 1 THEN  5605 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5605` = 1 THEN  5605 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5606` = 1 THEN  5606 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5606` = 1 THEN  5606 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5701` = 1 THEN  5701 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5701` = 1 THEN  5701 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5702` = 1 THEN  5702 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5702` = 1 THEN  5702 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5703` = 1 THEN  5703 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5703` = 1 THEN  5703 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5704` = 1 THEN  5704 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5704` = 1 THEN  5704 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5705` = 1 THEN  5705 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5705` = 1 THEN  5705 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5706` = 1 THEN  5706 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5706` = 1 THEN  5706 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5801` = 1 THEN  5801 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5801` = 1 THEN  5801 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5802` = 1 THEN  5802 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5802` = 1 THEN  5802 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5803` = 1 THEN  5803 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5803` = 1 THEN  5803 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `5804` = 1 THEN  5804 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `5804` = 1 THEN  5804 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6101` = 1 THEN  6101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6101` = 1 THEN  6101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6102` = 1 THEN  6102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6102` = 1 THEN  6102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6103` = 1 THEN  6103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6103` = 1 THEN  6103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6104` = 1 THEN  6104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6104` = 1 THEN  6104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6105` = 1 THEN  6105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6105` = 1 THEN  6105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6106` = 1 THEN  6106 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6106` = 1 THEN  6106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6107` = 1 THEN  6107 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6107` = 1 THEN  6107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6108` = 1 THEN  6108 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6108` = 1 THEN  6108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6109` = 1 THEN  6109 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6109` = 1 THEN  6109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6110` = 1 THEN  6110 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6110` = 1 THEN  6110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6111` = 1 THEN  6111 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6111` = 1 THEN  6111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6112` = 1 THEN  6112 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6112` = 1 THEN  6112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6113` = 1 THEN  6113 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6113` = 1 THEN  6113 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6115` = 1 THEN  6115 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6115` = 1 THEN  6115 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6116` = 1 THEN  6116 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6116` = 1 THEN  6116 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6117` = 1 THEN  6117 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6117` = 1 THEN  6117 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6201` = 1 THEN  6201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6201` = 1 THEN  6201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6202` = 1 THEN  6202 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6202` = 1 THEN  6202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6203` = 1 THEN  6203 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6203` = 1 THEN  6203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6204` = 1 THEN  6204 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6204` = 1 THEN  6204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6205` = 1 THEN  6205 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6205` = 1 THEN  6205 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6206` = 1 THEN  6206 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6206` = 1 THEN  6206 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6301` = 1 THEN  6301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6301` = 1 THEN  6301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6302` = 1 THEN  6302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6302` = 1 THEN  6302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6303` = 1 THEN  6303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6303` = 1 THEN  6303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6304` = 1 THEN  6304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6304` = 1 THEN  6304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6305` = 1 THEN  6305 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6305` = 1 THEN  6305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6306` = 1 THEN  6306 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6306` = 1 THEN  6306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6307` = 1 THEN  6307 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6307` = 1 THEN  6307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6308` = 1 THEN  6308 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6308` = 1 THEN  6308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6309` = 1 THEN  6309 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6309` = 1 THEN  6309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `6310` = 1 THEN  6310 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `6310` = 1 THEN  6310 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7101` = 1 THEN  7101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7101` = 1 THEN  7101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7102` = 1 THEN  7102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7102` = 1 THEN  7102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7103` = 1 THEN  7103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7103` = 1 THEN  7103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7104` = 1 THEN  7104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7104` = 1 THEN  7104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7105` = 1 THEN  7105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7105` = 1 THEN  7105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7106` = 1 THEN  7106 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7106` = 1 THEN  7106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7107` = 1 THEN  7107 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7107` = 1 THEN  7107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7108` = 1 THEN  7108 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7108` = 1 THEN  7108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7109` = 1 THEN  7109 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7109` = 1 THEN  7109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7110` = 1 THEN  7110 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7110` = 1 THEN  7110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7201` = 1 THEN  7201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7201` = 1 THEN  7201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7202` = 1 THEN  7202 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7202` = 1 THEN  7202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7203` = 1 THEN  7203 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7203` = 1 THEN  7203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7301` = 1 THEN  7301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7301` = 1 THEN  7301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7302` = 1 THEN  7302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7302` = 1 THEN  7302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7303` = 1 THEN  7303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7303` = 1 THEN  7303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7304` = 1 THEN  7304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7304` = 1 THEN  7304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7305` = 1 THEN  7305 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7305` = 1 THEN  7305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7306` = 1 THEN  7306 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7306` = 1 THEN  7306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7307` = 1 THEN  7307 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7307` = 1 THEN  7307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7308` = 1 THEN  7308 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7308` = 1 THEN  7308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7309` = 1 THEN  7309 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7309` = 1 THEN  7309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7401` = 1 THEN  7401 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7401` = 1 THEN  7401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7402` = 1 THEN  7402 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7402` = 1 THEN  7402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7403` = 1 THEN  7403 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7403` = 1 THEN  7403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7404` = 1 THEN  7404 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7404` = 1 THEN  7404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7405` = 1 THEN  7405 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7405` = 1 THEN  7405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7406` = 1 THEN  7406 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7406` = 1 THEN  7406 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7407` = 1 THEN  7407 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7407` = 1 THEN  7407 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `7408` = 1 THEN  7408 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `7408` = 1 THEN  7408 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8101` = 1 THEN  8101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8101` = 1 THEN  8101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8102` = 1 THEN  8102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8102` = 1 THEN  8102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8103` = 1 THEN  8103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8103` = 1 THEN  8103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8104` = 1 THEN  8104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8104` = 1 THEN  8104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8105` = 1 THEN  8105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8105` = 1 THEN  8105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8106` = 1 THEN  8106 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8106` = 1 THEN  8106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8107` = 1 THEN  8107 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8107` = 1 THEN  8107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8108` = 1 THEN  8108 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8108` = 1 THEN  8108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8109` = 1 THEN  8109 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8109` = 1 THEN  8109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8111` = 1 THEN  8111 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8111` = 1 THEN  8111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8112` = 1 THEN  8112 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8112` = 1 THEN  8112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8201` = 1 THEN  8201 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8201` = 1 THEN  8201 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8202` = 1 THEN  8202 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8202` = 1 THEN  8202 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8203` = 1 THEN  8203 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8203` = 1 THEN  8203 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8204` = 1 THEN  8204 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8204` = 1 THEN  8204 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8205` = 1 THEN  8205 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8205` = 1 THEN  8205 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8206` = 1 THEN  8206 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8206` = 1 THEN  8206 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8207` = 1 THEN  8207 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8207` = 1 THEN  8207 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8301` = 1 THEN  8301 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8301` = 1 THEN  8301 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8302` = 1 THEN  8302 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8302` = 1 THEN  8302 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8303` = 1 THEN  8303 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8303` = 1 THEN  8303 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8304` = 1 THEN  8304 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8304` = 1 THEN  8304 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8305` = 1 THEN  8305 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8305` = 1 THEN  8305 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8306` = 1 THEN  8306 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8306` = 1 THEN  8306 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8307` = 1 THEN  8307 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8307` = 1 THEN  8307 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8308` = 1 THEN  8308 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8308` = 1 THEN  8308 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8309` = 1 THEN  8309 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8309` = 1 THEN  8309 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8310` = 1 THEN  8310 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8310` = 1 THEN  8310 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8311` = 1 THEN  8311 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8311` = 1 THEN  8311 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8312` = 1 THEN  8312 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8312` = 1 THEN  8312 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8313` = 1 THEN  8313 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8313` = 1 THEN  8313 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8314` = 1 THEN  8314 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8314` = 1 THEN  8314 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8401` = 1 THEN  8401 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8401` = 1 THEN  8401 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8402` = 1 THEN  8402 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8402` = 1 THEN  8402 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8403` = 1 THEN  8403 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8403` = 1 THEN  8403 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8404` = 1 THEN  8404 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8404` = 1 THEN  8404 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8405` = 1 THEN  8405 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8405` = 1 THEN  8405 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8406` = 1 THEN  8406 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8406` = 1 THEN  8406 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8407` = 1 THEN  8407 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8407` = 1 THEN  8407 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8408` = 1 THEN  8408 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8408` = 1 THEN  8408 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8409` = 1 THEN  8409 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8409` = 1 THEN  8409 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8410` = 1 THEN  8410 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8410` = 1 THEN  8410 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8411` = 1 THEN  8411 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8411` = 1 THEN  8411 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8412` = 1 THEN  8412 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8412` = 1 THEN  8412 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8413` = 1 THEN  8413 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8413` = 1 THEN  8413 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8414` = 1 THEN  8414 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8414` = 1 THEN  8414 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8415` = 1 THEN  8415 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8415` = 1 THEN  8415 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8416` = 1 THEN  8416 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8416` = 1 THEN  8416 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8417` = 1 THEN  8417 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8417` = 1 THEN  8417 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8418` = 1 THEN  8418 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8418` = 1 THEN  8418 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8419` = 1 THEN  8419 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8419` = 1 THEN  8419 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8420` = 1 THEN  8420 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8420` = 1 THEN  8420 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `8421` = 1 THEN  8421 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `8421` = 1 THEN  8421 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9101` = 1 THEN  9101 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9101` = 1 THEN  9101 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9102` = 1 THEN  9102 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9102` = 1 THEN  9102 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9103` = 1 THEN  9103 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9103` = 1 THEN  9103 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9104` = 1 THEN  9104 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9104` = 1 THEN  9104 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9105` = 1 THEN  9105 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9105` = 1 THEN  9105 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9106` = 1 THEN  9106 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9106` = 1 THEN  9106 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9107` = 1 THEN  9107 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9107` = 1 THEN  9107 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9108` = 1 THEN  9108 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9108` = 1 THEN  9108 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9109` = 1 THEN  9109 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9109` = 1 THEN  9109 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9110` = 1 THEN  9110 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9110` = 1 THEN  9110 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9111` = 1 THEN  9111 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9111` = 1 THEN  9111 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9112` = 1 THEN  9112 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9112` = 1 THEN  9112 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9113` = 1 THEN  9113 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9113` = 1 THEN  9113 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9114` = 1 THEN  9114 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9114` = 1 THEN  9114 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9115` = 1 THEN  9115 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9115` = 1 THEN  9115 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9116` = 1 THEN  9116 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9116` = 1 THEN  9116 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9117` = 1 THEN  9117 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9117` = 1 THEN  9117 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9118` = 1 THEN  9118 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9118` = 1 THEN  9118 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9119` = 1 THEN  9119 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9119` = 1 THEN  9119 END IS NOT NULL UNION
SELECT id, (SELECT 1), CASE  WHEN `9120` = 1 THEN  9120 END , NOW(), NOW() FROM src_cul_vid_dstr WHERE CASE  WHEN `9120` = 1 THEN  9120 END IS NOT NULL;


-- Copiar y crear tabla de transgenicas

CREATE TABLE flujoapp.scr_transgenicas SELECT * FROM flujo_genico.src_transgenicas_copy;

-- Distribución de transgenicos en chile temporada 2012-2013

INSERT INTO dstr_region (id_taxa, type, code, created_at, updated_at)

SELECT especie,(SELECT 4) ,region, NOW(),NOW() FROM  `src_transg_georef` GROUP BY CONCAT( especie, region );

INSERT INTO dstr_comuna (id_taxa, type, code, created_at, updated_at)

SELECT especie,(SELECT 4) ,comuna, NOW(),NOW() FROM  `src_transg_georef` GROUP BY CONCAT( especie, comuna );



INSERT INTO `zz_auxtax` (id, name)
select id, familia from src_cultivadas group by familia union
select id, familia from src_introducidas group by familia union
select id, familia from src_nativas group by familia union
select id, FAMILIA from scr_transgenicas group by FAMILIA ;

INSERT INTO `tax_familia_src` (name)
select DISTINCT name from zz_auxtax;

TRUNCATE `zz_auxtax` ; 
INSERT INTO `zz_auxtax` (id, name)
select id, genero from src_cultivadas group by genero union
select id, genero from src_introducidas group by genero union
select id, genero from src_nativas group by genero union
select id, GENERO from scr_transgenicas group by GENERO ;

INSERT INTO `tax_genero_src` (name)
select DISTINCT name from zz_auxtax;

TRUNCATE `zz_auxtax` ; 
INSERT INTO `zz_auxtax` (id, name)
select id, especie from src_cultivadas group by especie union
select id, especie from src_introducidas group by especie union
select id, especie from src_nativas group by especie union
select id, ESPECIE from scr_transgenicas group by ESPECIE ;

INSERT INTO `tax_especie_src` (name)
select DISTINCT name from zz_auxtax;


TRUNCATE tax_familia;
INSERT INTO tax_familia (id_taxa, type, code, created_at, updated_at)
select src_cultivadas.id, (select 1), tax_familia_src.id, now(), now() from src_cultivadas inner join tax_familia_src on (src_cultivadas.familia=tax_familia_src.name) union
select src_introducidas.id, (select 2), tax_familia_src.id, now(), now() from src_introducidas inner join tax_familia_src on (src_introducidas.familia=tax_familia_src.name) union
select src_nativas.id, (select 3), tax_familia_src.id, now(), now() from src_nativas inner join tax_familia_src on (src_nativas.familia=tax_familia_src.name)union
select scr_transgenicas.id, (select 4), tax_familia_src.id, now(), now() from scr_transgenicas inner join tax_familia_src on (scr_transgenicas.familia=tax_familia_src.name);

TRUNCATE tax_genero;
INSERT INTO tax_genero (id_taxa, type, code, created_at, updated_at)
select src_cultivadas.id, (select 1), tax_genero_src.id, now(), now() from src_cultivadas inner join tax_genero_src on (src_cultivadas.genero=tax_genero_src.name) union
select src_introducidas.id, (select 2), tax_genero_src.id, now(), now() from src_introducidas inner join tax_genero_src on (src_introducidas.genero=tax_genero_src.name) union
select src_nativas.id, (select 3), tax_genero_src.id, now(), now() from src_nativas inner join tax_genero_src on (src_nativas.genero=tax_genero_src.name)union
select scr_transgenicas.id, (select 4), tax_genero_src.id, now(), now() from scr_transgenicas inner join tax_genero_src on (scr_transgenicas.genero=tax_genero_src.name);

TRUNCATE tax_especie;
INSERT INTO tax_especie (id_taxa, type, code, created_at, updated_at)
select src_cultivadas.id, (select 1), tax_especie_src.id, now(), now() from src_cultivadas inner join tax_especie_src on (src_cultivadas.especie=tax_especie_src.name) union
select src_introducidas.id, (select 2), tax_especie_src.id, now(), now() from src_introducidas inner join tax_especie_src on (src_introducidas.especie=tax_especie_src.name) union
select src_nativas.id, (select 3), tax_especie_src.id, now(), now() from src_nativas inner join tax_especie_src on (src_nativas.especie=tax_especie_src.name)union
select scr_transgenicas.id, (select 4), tax_especie_src.id, now(), now() from scr_transgenicas inner join tax_especie_src on (scr_transgenicas.especie=tax_especie_src.name);

-- Tabla de nombres comúnes.
insert into nombre_comun (id_taxa, type, language, name)

select id, (select 1),(select 'es'), nombre_comun from src_cultivadas union
select id, (select 2),(select 'es'), nombre from src_introducidas union
-- select id, (select 3), nombre_comun from src_nativas union -- no tiene nombre comunes las nativas
select id, (select 4),(select 'es'), nombre from scr_transgenicas union
select id, (select 4),(select 'en'), `nombre ingles` from scr_transgenicas

insert into origen (id_taxa, type, name)
select id, (select 1), reg_diversidad from src_cultivadas union
select id, (select 2), origen from src_introducidas;


create table flujoapp.dstr_region_src select * from flujo_genico.test_distribucion_region;

create table flujoapp.dstr_provincia_src select * from flujo_genico.test_distribucion_provincia;

create table flujoapp.dstr_comuna_src select * from flujo_genico.test_distribucion_comuna;


-- Crear tabla de nombre de regiones
-- migrations 
-- php artisan migrate:make create_region_name_table
-- php artisan migrate

INSERT INTO flujoapp.dstr_region_name (id, name, created_at, updated_at	)

SELECT id, name, NOW(), NOW() FROM flujo_genico.test_distribucion_region;

-- Crear tabla de nombre de comunas
-- migrations 
-- php artisan migrate:make create_comunas_name_table
-- php artisan migrate

INSERT INTO flujoapp.dstr_comuna_name (id, name, created_at, updated_at	)

SELECT id, name, NOW(), NOW() FROM flujo_genico.test_distribucion_comuna;





















